---
- name: Get token for worker node join
  set_fact:
    join_cmd: "{{ hostvars['vm-k8s-1']['worker_join_cmd'] }}"

# Once https://github.com/kubernetes/kubeadm/issues/659 is resolved we can drop the unsafe flag and get/use the hash
- name: Join the cluster as worker
  command: "{{ join_cmd }}"
  when:
    - join_cmd is defined and join_cmd != ""
  register: out

- debug: var=out
